project:
  type: website
  output-dir: _site
  preview:
    navigate: false
  resources:
    - downloads/*.xlsx
    - downloads/*.csv
    - assets/rigi-responsive.js
    - assets/planes_inversion.js
    - assets/importaciones.js

website:
  title: "Monitor de Proyectos RIGI"
  site-url: "https://monitor-rigi-desip-iiep.github.io/RIGI/"
  repo-url: "https://github.com/monitor-rigi-desip-iiep/RIGI"
  page-footer:
    left: "DESIP-IIEP"
    right: "IIEP"
  navbar:
    background: "#0B132B"
    foreground: "#FFFFFF"
    left:
      - href: index.qmd
        text: Informe
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 3
    page-layout: full
    code-fold: true
    code-tools: false
    smooth-scroll: true

execute:
  echo: false
  warning: false
  message: false
